### ISSUE TITLE
Only errors

### ISSUE THREAD

**Issue by buzink** [dawnlabs/alchemy#30] opened 2017-12-26 07:53 UTC
Looks stunning but doesn't work at all. After adding three jpegs and clicking convert to pdf I get only command line like errors

**Comment by mfix22** [comment] 2017-12-31 04:21
Hey @buzink thanks for the issue! Can you post the exact image names here? Maybe we are still having path issues.

**Comment by qnibru** [comment] 2018-03-11 17:06
Hi !
I have the same problem
It does this : 
![capture d ecran 86](https://user-images.githubusercontent.com/36766244/37256072-27144452-2556-11e8-8bbb-522da073439b.png)
![capture d ecran 87](https://user-images.githubusercontent.com/36766244/37256083-3ba23b72-2556-11e8-86a6-8ca783fc9bfe.png)

**Comment by mfix22** [comment] 2018-06-01 01:27
This is definitely a duplicate of #31 😄We will try and fix this soon.

**Closed by mfix22** 2018-06-01 01:27 UTC
Labels: bug
